"""make rlhf responses nullable

Revision ID: 4ea5ab120c0e
Revises: ea8e069f1963
Create Date: 2026-05-18 22:15:36.680949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ea5ab120c0e'
down_revision: Union[str, Sequence[str], None] = 'ea8e069f1963'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rlhf_feedback', 'chosen_response',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('rlhf_feedback', 'rejected_response',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rlhf_feedback', 'rejected_response',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('rlhf_feedback', 'chosen_response',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
