"""Reverted to a clean state

Revision ID: 6e8573a51985
Revises: bfe4cbd47ab8
Create Date: 2026-05-17 22:01:06.989824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e8573a51985'
down_revision: Union[str, Sequence[str], None] = 'bfe4cbd47ab8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('conversations_repository_id_fkey', 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'repositories', ['repository_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.create_foreign_key('conversations_repository_id_fkey', 'conversations', 'repositories', ['repository_id'], ['id'])
    # ### end Alembic commands ###
