"""Add GitHub fields to Repository

Revision ID: 804bd97e0be4
Revises: ff46de556ec4
Create Date: 2026-04-16 16:24:44.795362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '804bd97e0be4'
down_revision: Union[str, Sequence[str], None] = 'ff46de556ec4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('github_url', sa.String(), nullable=False))
    op.add_column('repositories', sa.Column('default_branch', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'default_branch')
    op.drop_column('repositories', 'github_url')
    # ### end Alembic commands ###
